inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - test_prof/rubocop

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'

# revisit this once Ruby 3 is out
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  AllowURI: true

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Style/AndOr:
  EnforcedStyle: 'conditionals'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'detect'
    find_all: 'select'

Style/WordArray:
  MinSize: 3

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Alias:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
  EnforcedColonStyle: 'key'
  EnforcedHashRocketStyle: 'key'

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'spec/parser/treetop_parser_spec.rb'

RSpec/AggregateFailures:
  Enabled: true
  Include:
    - 'spec/**/*.rb'

RSpec/DescribeClass:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10
