inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec
  - test_prof/rubocop

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/gobstones/runner/execution_context.rb'

Naming/MethodParameterName:
  Enabled: true
  AllowedNames: on, x, y

Metrics/BlockNesting:
  Max: 2

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Max: 21

Layout/LineLength:
  Max: 120
  AllowURI: true

Layout/HashAlignment:
  Enabled: false
  EnforcedColonStyle: 'key'
  EnforcedHashRocketStyle: 'key'

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'spec/parser/treetop_parser_spec.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# Preferimos que los nombres de archivos no queden tan acoplados al objeto que estan testeando
RSpec/SpecFilePathFormat:
  Enabled: false

Style/AndOr:
  EnforcedStyle: 'conditionals'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'detect'
    find_all: 'select'

Style/MixinUsage:
  Exclude:
    - 'lib/gobstones/cli/runner.rb'
    - 'spec/spec_helper.rb'

Style/WordArray:
  MinSize: 3

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Alias:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

RSpec/DescribeMethod:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: true

RSpec/ExpectActual:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 13

RSpec/MultipleMemoizedHelpers:
  Max: 10
  AllowSubject: true
