language: ruby
sudo: false
rvm:
  - 2.7.0
before_install:
  - gem install bundler # workaround - https://github.com/travis-ci/travis-ci/issues/9383
install:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rubocop
  - bundle exec rake spec
