#!/usr/bin/env ruby

$:.unshift File.dirname(__FILE__) + '/lib'

require 'gobstones/cli/cli'
require 'gobstones/lang/all'
require 'gobstones/extensions/all'
require 'gobstones/runner/all'

gbs_file = ARGV[0]
if gbs_file
  Gobstones::CLI::Runner.run(gbs_file)
else
  puts 'No Gobstones program specified'
end
