require 'gobstones/runner/errors/boom_error'
require 'gobstones/runner/errors/definition_not_found_error'
require 'gobstones/runner/errors/empty_cell_error'
require 'gobstones/runner/errors/gbs_runtime_error'
require 'gobstones/runner/errors/gbs_type_error'
require 'gobstones/runner/errors/undefined_variable_error'
require 'gobstones/runner/errors/out_of_board_error'
require 'gobstones/runner/errors/wrong_arguments_error'